### ISSUE TITLE
2019.04 TODO

### ISSUE THREAD

**Issue by nyybb** [betterfly4202/theme-joo#9]
# Backend
- [x] Infra 구성
- [ ] Theme 기본정보 Scheme 설계
- [ ] Theme CRUD

# Frontend
- [x] Angular 기본 구조 설계
- [ ] Functional Javascript 구성
- [ ] Theme 리스트 화면 구성
